Import('env', 'arch', 'messaging', 'common', 'visionipc')

libs = [common, messaging, visionipc]

if arch == "comma_arm64":
  camera_obj = env.Object(['cameras/camera_qcom2.cc', 'cameras/camera_common.cc', 'cameras/spectra.cc',
                           'cameras/cdm.cc', 'sensors/ox03c10.cc', 'sensors/os04c10.cc'])
  env.Program('camerad', ['main.cc', camera_obj], LIBS=libs)
else:
  # Linux PCs and Android-hosted LXC use Camera2 through the shared-buffer bridge.
  env.Program('camerad', ['android_camera.cc'], LIBS=libs)
