Import('env', 'arch', 'common', 'messaging')

if arch != "Darwin":
  # [op9] usb (libusb) added so pandad talks to the OnePlus 9's external USB panda
  libs = [common, messaging, 'pthread', 'usb-1.0']
  panda = env.Library('panda', ['panda.cc', 'spi.cc', 'usb.cc'])

  env.Program('pandad', ['main.cc', 'pandad.cc', 'panda_safety.cc'], LIBS=[panda] + libs)

  if GetOption('extras'):
    env.Program('tests/test_pandad_canprotocol', ['tests/test_pandad_canprotocol.cc'], LIBS=[panda] + libs)
